### ISSUE TITLE
Missing some samples at the end of file

### ISSUE THREAD

**Issue by Skyavx** [MeguminSama/genshin-audio-extractor#3]
Hello. Thank you so much for your script. It works wonders on extracting the audio. 

The only issue I've found is some files end up cut at the end, almost always a few milliseconds. I don't know if this problem is caused by one of the used tools, my guess is that the frames are either 2048 or 4096 samples and they are cut on the last frame that is >= 2048 or >= 4096. So the last few milliseconds (a thousand samples or so) are left out from the output file.

Some files are not affected as they may have had silence at the end so it's not noticeable. Some examples are: /English/ External0_1, External0_10, External0_30.

Any ideas on what could be causing the issue?

**Comment by MeguminSama** [comment]
Hey there,
thanks for the report, and I'm glad my mess of a program was useful to someone :)

I know there have been issues with some sound banks not extracting. but I hadn't noticed any audio cutting off

I'll try and figure out what's going on here and get back to you!

**Comment by sohro-da** [comment]
> Some files are not affected as they may have had silence at the end so it's not noticeable. Some examples are: /English/ External0_1, External0_10, External0_30.

And lot (maybe all of them) of Japanese voice over files are in the same condition (edited: I mean, they trimmed at the end) as you mentioned.
[External0_327.zip](https://github.com/MeguminSama/genshin-audio-extractor/files/5623302/External0_327.zip)
I really appreciate you guys for this tool!

**Comment by YunYunHelp** [comment]
Hi MeguminSama, your program or code will help me a lot, but I can't do anything because I don't know JavaScript, can you explain in detail what I need to do to extract sounds.
I would be very grateful!

**Comment by NurMarvin** [comment]
> Hi MeguminSama, your program or code will help me a lot, but I can't do anything because I don't know JavaScript, can you explain in detail what I need to do to extract sounds.
> I would be very grateful!

There isn't much to misunderstand, there's a usage in the README file which is pretty self-explanatory. You just need to install NodeJS and then everything listed there should work.

**Comment by MeguminSama** [comment]
Unfortunately I haven't been able to figure out what's causing this bug :/

Hopefully someone else interested in the project will find out eventually

I'll keep this issue open until it's figured out.

**Comment by alexpado** [comment]
Hi,

The main problem is to know which program fails to extract the audio completely.
I've tried to find any relevant cli argument for quickbms and vgmstream, but I can't really understand some of them, so I'm maybe missing something here.

I've also looked after another wem to wav converter to check if it wasn't lost in this conversion step, but for now I didn't find any working converter. I'll continue to search for one though.

Anyway, thanks for this amazing program, which is very useful :)

**Comment by MeguminSama** [comment]
@alexpado if you do find a better converter, please let me know so I can implement it. Unfortunately I think it's the third party tools we're using causing the problems atm :/

**Comment by alexpado** [comment]
@MeguminSama I've installed Winamp with the vgmstream decoder and I don't have any audio issues.

It seems the issue is coming from the vgmstream-cli program... I'll continue my investigation on that matter


*Edit for clarification:* I'm using the wem files extracted by your script itself that are then used for the conversion process
