### ISSUE TITLE
Output folder name cuts off if there is a "." in the pck file name

### ISSUE THREAD

**Issue by Merrick919** [MeguminSama/genshin-audio-extractor#7]
![Screenshot 2021-02-05 001300](https://user-images.githubusercontent.com/37953774/106932904-40ada380-6753-11eb-9a8d-26720ec9e6fd.png)

The pck files with names starting with "Music_1" have all been merged into a single folder.

**Comment by MeguminSama** [comment]
huh github autoclosed it...

Could you please try the latest commit?

**Comment by MeguminSama** [comment]
Newer versions of genshin started changing the file format, hopefully this should fix it. Please let me know if the problem persists.

**Comment by Merrick919** [comment]
It works now, thank you.
