### ISSUE TITLE
Error with .pck file extraction. /processing/Music folders generated, but no file output. Help please!

### ISSUE THREAD

**Issue by brybalicious** [MeguminSama/genshin-audio-extractor#8]
`$  node --trace-warnings decode.js --input ./genshinmusic`

Found 37 pck files
(node:1826) UnhandledPromiseRejectionWarning: Error: Command failed: /mnt/c/Users/xyz/Git/genshin-audio-extractor/libs/quickbms.exe /mnt/c/Users/xyz/Git/genshin-audio-extractor/libs/wavescan.bms /mnt/c/Users/xyz/Git/genshin-audio-extractor/genshinmusic/Music0.pck processing/Music0
Error: No such file or directory

QuickBMS generic files extractor and reimporter 0.8.3
by Luigi Auriemma
e-mail: me@aluigi.org
web:    aluigi.org
        (Jan 21 2018 - 15:18:31)

                   quickbms.aluigi.org  Homepage
                            zenhax.com  ZenHAX Forum
                               @zenhax  Twitter & Scripts

- open input file /mnt/c/Users/xyz/Git/genshin-audio-extractor/genshinmusic/Music0.pck

- error in src\file.c line 465: fdnum_open()

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:1826) Error: Command failed: /mnt/c/Users/xyz/Git/genshin-audio-extractor/libs/quickbms.exe /mnt/c/Users/xyz/Git/genshin-audio-extractor/libs/wavescan.bms /mnt/c/Users/xyz/Git/genshin-audio-extractor/genshinmusic/Music0.pck processing/Music0
Error: No such file or directory

QuickBMS generic files extractor and reimporter 0.8.3
by Luigi Auriemma
e-mail: me@aluigi.org
web:    aluigi.org
        (Jan 21 2018 - 15:18:31)

                   quickbms.aluigi.org  Homepage
                            zenhax.com  ZenHAX Forum
                               @zenhax  Twitter & Scripts

- open input file /mnt/c/Users/xyz/Git/genshin-audio-extractor/genshinmusic/Music0.pck

- error in src\file.c line 465: fdnum_open()

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
(node:1826) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)

**Comment by MeguminSama** [comment]
it looks like you're trying to run this in Windows Subsystem for Linux.

could you please try it on Windows in powershell/command prompt?

let me know if it continues

**Comment by brybalicious** [comment]
gotcha. Thanks for quick reply! Just don;t have npm installed there

**Comment by brybalicious** [comment]
okay @MeguminSama turns out it's just a problem on wsl. Works fine with Node.js for windows, using the bundled node.js command prompt. Thanks for the suggestion! And for the repo :)

**Comment by MeguminSama** [comment]
Glad it's working now.

Unfortunately a few of the tools used are windows-only so it's incompatible with linux currently
